project_id: "372633"
api_token: "<api-token-here>"
base_path: "../app/src/main"
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
- source: "res/values/strings.xml"
  dest: "strings.xml"
  translation: "res/values-%android_code%/%original_file_name%"
